remote-theme: 18F/uswds-jekyll
title: Knights of Columbus 4th Degree Pope John Paul II Assembly 2939, Gilroy/Morgan Hill,CA
description: Knights of Columbus 4th Degree Pope John Paul II Assembly 2939, Gilroy/Morgan Hill,CA

frontpagestuff:
  callout:
    alt: Knights of Columbus 4th Degree
    text:
  callout: 
    alt: Pope John Paul II Assembly 2939 Gilroy/Morgan Hill, CA
    text: 
  button:
    text: Contact
    href: https://google.com
