remote-theme: 18F/uswds-jekyll
title: St. Pope John Paul II Assembly #2939
description: Knights of Columbus 4th Degree Assembly 2939, Gilroy/Morgan Hill,CA

styles:
  - main.css

hero:
  callout: 
    alt: St. Pope John Paul II Assembly 2939
    text: Gilroy/Morgan Hill, CA
  button:
    text: Contact
    href: https://google.com
