remote-theme: 18F/uswds-jekyll
title: St. Pope John Paul II Assembly 2939
description: Knights of Columbus 4th Degree Assembly 2939, Gilroy/Morgan Hill,CA

frontpagestuff:	
  callout:
    alt:
    text:
